[build]
  # Docusaurus outputs to build directory
  publish = "build"

  # Docusaurus build command
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	# baseUrl = "https://webreaper.dev"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.85
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.9

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

  # Audit homepage
  [[plugins.inputs.audits]]
    path = "https://webreaper.dev"

  # Audit docs introduction
  [[plugins.inputs.audits]]
    path = "https://webreaper.dev/docs/intro"

  # Audit blog section
  [[plugins.inputs.audits]]
    path = "https://webreaper.dev/blog"